"""users

Revision ID: a633f85d4d40
Revises: 7ded292ea60e
Create Date: 2020-04-27 16:51:55.906273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a633f85d4d40'
down_revision = '7ded292ea60e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orchard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rows', sa.Integer(), nullable=True),
    sa.Column('trees', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orchard')
    # ### end Alembic commands ###
